allow to configure networks that can access postgres and that can do replication

diff --git a/files/pg_createconfig_patroni b/files/pg_createconfig_patroni
--- a/files/pg_createconfig_patroni
+++ b/files/pg_createconfig_patroni
@@ -6,6 +6,7 @@
 # * [improve brittle pg_lsclusters parsing](https://bugs.debian.org/953157)
 # * [rerunning pg_createconfig_patroni --force will keep on increasing the port number or fail if reusing the same port](https://bugs.debian.org/953162)
 # * [doesn't clean up /etc/patroni/$VERSION-$CLUSTER.vip file before appending to it](https://bugs.debian.org/953147)
+# * allow to set network address of allowed replication hosts via --repl-network
 
 for i in "$@"
 do
@@ -16,6 +17,10 @@ case $i in
     ;;
     --network=*)
     NETWORK="${i#*=}"
+    shift # past argument=value
+    ;;
+    --repl-network=*)
+    REPL_NETWORK="${i#*=}"
     shift # past argument=value
     ;;
     --port=*)
@@ -204,6 +209,16 @@ if [ -z "$NETWORK" ]; then
     fi
 fi
 
+if [ -z "$REPL_NETWORK" ]; then
+    if [ -x /bin/ip ]; then
+        REPL_NETWORK=$(/bin/ip -4 route get 8.8.8.8 | grep ^8.8.8.8 | sed -e s/.*src.// -e s/\ .*//g -e s/\.[0-9]*$/.0/)/24
+    else
+        echo "iproute2 package missing, cannot determine network and --replication-network is not set"
+        rm -f $CONFIG_FILE
+        exit 1
+    fi
+fi
+
 # add remaining patroni configuration from template
 cat /etc/patroni/config.yml.in |		\
     sed -e "s/@VERSION@/${VERSION}/g"		\
@@ -212,6 +227,7 @@ cat /etc/patroni/config.yml.in |		\
         -e "s/@HOSTIP@/${HOSTIP}/g"		\
         -e "s/@LISTEN_VIP@/${LISTEN_VIP}/g"	\
         -e "s#@NETWORK@#${NETWORK}#g"		\
+        -e "s#@REPL_NETWORK@#${REPL_NETWORK}#g"	\
         -e "s/@API_PORT@/${API_PORT}/g"		\
         -e "s/@PORT@/${PORT}/g"			\
         -e "s/@DCS_CONFIG@/${DCS_CONFIG}/g"	\
